apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${{values.k8sResource.name}}-network-policy
  labels:
    app: app
spec:
  podSelector:
    matchLabels:
      app: app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    # 共有ゲートウェイからの通信を許可
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: envoy-gateway-system
    ports:
    - protocol: TCP
      port: 8080
  egress: []
