apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: Go echo web application template
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner}}
  providesApis:
    - ${{values.name}}
