apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{values.k8sResource.name}}-config
  labels:
    app: app
data:
  PORT: "8080"
  LOG_LEVEL: "info"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.observability.svc:4317"
  OTEL_SERVICE_NAME: "${{values.k8sResource.name}}"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=${{values.k8sResource.namespace}},deployment.environment=development"
